name: {$name}
main: {$groupId}.{$artifactId}.{$name}
version: {$version}
author: JavaPortals
website: {$website}
softdepend: [Vault]
commands:
  {$artifactId}:
    description: "Speak in the {$name}"
    aliases: [sc, s]
  toggle{$artifactId}:
    description: "Toggle the {$name}"
    aliases: [tsc, ts]
  reload{$artifactId}:
    description: "Reload the {$name} configuration"
    aliases: [rsc, rs]
permissions:
  {$artifactId}.*:
    description: This permission will give access to all {$name} permissions
    default: op
    children:
      {$artifactId}.speak: true
      {$artifactId}.listen: true
      {$artifactId}.color: true
      {$artifactId}.reload: true
      {$artifactId}.update: true
  {$artifactId}.speak:
    default: op
    description: This permission will allow the user to speak to the {$name}.
  {$artifactId}.listen:
    default: op
    description: This permission will allow the user to receive {$name} messages
  {$artifactId}.color:
    default: op
    description: This permission will allow the user to use colors in the {$name}
  {$artifactId}.reload:
    default: op
    description: This permission will allow the user to reload the {$name} configuration
  {$artifactId}.update:
    default: op
    description: This permission will tell the user if a update is available